[versions]
agp = "9.3.1"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.14.0"
activityKtx = "1.13.0"
constraintlayout = "2.2.2"
postgrestKt = "3.7.0"
storageKt = "3.7.0"
authKt = "3.7.0"
retrofit = "3.0.0"
converterGson = "3.0.0"
loggingInterceptor = "5.4.0"
firebaseBom = "34.17.0"
firebaseMessaging = "25.1.1"
roomRuntime = "2.8.4"
roomCompiler = "2.8.4"
activityKtxVersion = "1.13.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activityKtx" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
postgrest-kt = { group = "io.github.jan-tennert.supabase", name = "postgrest-kt", version.ref = "postgrestKt" }
storage-kt = { group = "io.github.jan-tennert.supabase", name = "storage-kt", version.ref = "storageKt" }
auth-kt = { group = "io.github.jan-tennert.supabase", name = "auth-kt", version.ref = "authKt" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "converterGson" }
logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "loggingInterceptor" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging", version.ref = "firebaseMessaging" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "roomRuntime" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "roomCompiler" }
activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activityKtxVersion" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

